name: Enviar notificación por correo

on:
  push:
    branches:
      - main
      - feature_a
      - feature_b

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
    - name: Enviar correo
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        
        subject: ${{ env.subject }}
        body: "Se realizaron cambios en la rama ${{ github.ref_name }}."
        to: "${{ secrets.EMAIL_USERNAME }}"
        from: "${{ secrets.EMAIL_USERNAME }}"
