name: Send Notification Email

# cambio en branches main, feature_a o feature_b
on:
  push:
    branches:
      - main
      - feature_a
      - feature_b

jobs:
  email_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          # Configuración del servidor SMTP
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_USERNAME   }}
          password: ${{ secrets.SMTP_PASSWORD  }}
          
          # Configuración del correo
          subject: "Cambios en la rama ${{ github.ref_name }}"
          body: "Se han subido cambios a la rama ${{ github.ref_name }} del repositorio."
          to: "${{ secrets.SMTP_USERNAME  }}"
          from: "${{ secrets.SMTP_USERNAME  }}"
